<?php

namespace App;

use Cog\Contracts\Ban\Bannable as BannableContract;
use Cog\Laravel\Ban\Traits\Bannable;
use Illuminate\Database\Eloquent\Builder;

class Supporter extends User implements BannableContract
{
    use Bannable;
    protected $table = 'users';
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('supporter',function ( Builder $builder){
            $builder->whereNotNull('teacher_id');
        });
    }

    public function teacher()
    {
        return $this->belongsTo(Teacher::class);
    }

    //?
    public function course()
    {
        return $this->belongsTo(Course::class);
    }
}
