<?php

namespace App;
use Illuminate\Database\Eloquent\Builder;

class Teacher extends User
{
    protected $table = 'users';
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('teacher', function (Builder $builder) {
            $builder->whereNull('teacher_id');
        });
    }


    //create courses
    public function courses()
    {
        return $this->hasMany(Course::class,'teacher_id','id');

    }

    //add supporters
    public function supporters()
    {
        return $this->hasMany(Supporter::class);
    }

}
